development:
  adapter: mysql2
  database: attestation
  username: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: attestation_test
  username: root
  password:
  pool: 5
  timeout: 5000